# Generated by Django 4.2.7 on 2023-11-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_read_length_seconds_alter_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='read_length_seconds',
            new_name='read_length_minutes',
        ),
    ]
