# Generated by Django 4.2.7 on 2023-11-15 11:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_read_length_seconds_post_read_length_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=api.models.upload_cover_image),
        ),
    ]
