# Generated by Django 4.2.7 on 2023-11-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_list_created_at_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
